export const figmaAssets = {
  figmaBusinessPartners: "/figma-assets/image-fills/1958cc39abc0ad658a9c5454fb531e80c31f464e-optimized.jpg",
  figmaBuilding: "/figma-assets/image-fills/49ea5afcd08e354d2128485561e0136b723e384e.png",
  figmaFieldHero: "/figma-assets/image-fills/d50005e607480723ef80c8b7ba3864acdbcd1a39.png",
  figmaTeamPortrait: "/figma-assets/image-fills/3575adb86737d96194fbaf002a8bc285b11fb790.png",
  logoBlue: "/home/logo-blue.svg",
  logoWhite: "/home/footer-logo.svg",
  footerPattern: "/home/footer-pattern.svg",
  heroHome: "/home/hero.png",
  video: "/Webinar Card - horizontal tab.svg",
  play: "/home/play.svg",
  people: "/home/people.png",
  risk: "/home/risk-image.png",
  testimonial: "/home/testimonial.png",
  testimonialRing: "/home/testimonial-ring.png",
  news: "/home/news.png",
  contact: "/home/contact.png",
  caseStudy: "/home/case-study-remote.png",
  article: "/home/article.png",
  webinar: "/home/webinar.png",
  whoHero: "/home/who-hero.png",
  ourWorkFeature: "/home/our-work-feature-source.png",
  ourWorkTall: "/home/our-work-tall-source.png",
  ourWorkCard: "/what/our-work-card.png",
  impactGlobe: "/what/impact-globe.svg",
  productOrbit: "/what-product-orbit.svg",
  servicesCaseStudy: "/what/services-case-study.png",
  servicesTestimonialAvatar: "/what/services-testimonial-avatar.png",
  servicesTestimonialBg: "/what/services-testimonial-bg.png",
  insightsContentTab: "/insights/edit-flags/insights-content-tab.jpg",
  insightsNewsletter: "/insights/edit-flags/insights-newsletter.jpg",
  articlesContentTab: "/insights/edit-flags/articles-content-tab.jpg",
  articlesWhatWeDo: "/insights/edit-flags/articles-what-we-do.jpg",
  newsContentTab: "/insights/edit-flags/news-content-tab.jpg",
  newsWhatWeDo: "/insights/edit-flags/news-what-we-do.jpg",
  whatContentTab: "/what/edit-flags/what-content-tab.jpg",
  whatOurTeam: "/what/edit-flags/what-our-team.jpg",
  servicesContentTab: "/what/edit-flags/services-content-tab.jpg",
  workContentTab: "/what/edit-flags/work-content-tab.jpg",
  workServices: "/what/edit-flags/work-services.jpg",
  impactContentTab: "/what/edit-flags/impact-content-tab.jpg",
  impactHybrImpact: "/what/edit-flags/impact-hybr-impact.jpg",
  impactCountriesReached: "/what/edit-flags/impact-countries-reached.jpg",
  caseStudyServices: "/what/edit-flags/case-study-services.jpg",
  whoContentTab: "/who/edit-flags/who-content-tab.jpg",
  whoAboutUs: "/who/edit-flags/who-about-us.jpg",
  whoCareers: "/who/edit-flags/who-careers.jpg",
  aboutContentBar: "/who/edit-flags/about-content-bar.jpg",
  aboutValuePurposefulIntegrity: "/who/edit-flags/about-value-purposeful-integrity.jpg",
  aboutValueAppliedCreativity: "/who/edit-flags/about-value-applied-creativity.jpg",
  aboutValueActivelyEntrepreneurial: "/who/edit-flags/about-value-actively-entrepreneurial.jpg",
  aboutValueWorkWin: "/who/edit-flags/about-value-work-win.jpg",
  careersContentBar: "/who/edit-flags/careers-content-bar.jpg",
  careersWorking: "/who/edit-flags/careers-working.jpg",
  careersFellowship: "/who/edit-flags/careers-fellowship.jpg",
  careersAlphaAd: "/who/edit-flags/careers-alpha-ad.jpg",
  careersNewsletter: "/who/edit-flags/careers-newsletter.jpg",
} as const;

export const navigation = [
  { label: "Who We Are", href: "/who-we-are", key: "who" },
  { label: "What We Do", href: "/what-we-do", key: "what" },
  { label: "Insights", href: "/insights", key: "insights" },
] as const;

export const footerGroups = [
  {
    title: "Who We Are",
    links: [
      { label: "About Us", href: "/who-we-are/about-us" },
      { label: "Our Team", href: "/who-we-are/our-team" },
      { label: "Careers", href: "/who-we-are/careers" },
    ],
  },
  {
    title: "What We Do",
    links: [
      { label: "Our Services", href: "/what-we-do/services" },
      { label: "Our Products", href: "/what-we-do/products" },
      { label: "Our Work", href: "/what-we-do/our-work" },
      { label: "Our Impact", href: "/what-we-do/our-impact" },
    ],
  },
  {
    title: "Insights",
    links: [
      { label: "Articles & Posts", href: "/insights/articles" },
      { label: "Masterclasses", href: "/insights/webinars" },
      { label: "News & Updates", href: "/insights/news" },
    ],
  },
  {
    title: "Contact us",
    links: [
      { label: "hello@hybrgroup.net", href: "mailto:hello@hybrgroup.net" },
    ],
  },
] as const;

export const siteContent = {
  brand: "HYBR",
  footerCopyright: "\u00A9 2026 HYBR GROUP",
  socialLinks: ["Instagram", "Facebook", "TikTok", "LinkedIn", "X", "YouTube", "Medium"],
  wordpressEditable: [
    "Pages and section copy",
    "Navigation and footer labels",
    "Services, products, impact stats, and timeline entries",
    "Case studies, articles, webinars, and news",
    "Team members, careers, testimonials, and contact details",
    "Images and downloadable resources",
  ],
} as const;
